version: '3.7'
networks:
  default:
    external:
      name: pis-septemberlabs
services:
  webapp:
    tty: true
    build:
      context: ${PARENT_PWD}/capacitacion-webapp
    container_name: pis-septemberlabs_webapp
    command: yarn start
    ports:
      - '5002:5002'
    volumes:
      - "${PARENT_PWD}/capacitacion-webapp/src:/app/capacitacion-webapp/src"
      - "${PARENT_PWD}/capacitacion-webapp/public:/app/capacitacion-webapp/public"
